console.log('Buna' + 'ziua');
console.log('s' == 'S');
console.log('l' > 'm');
console.log('d' > 'r');
console.log('liviu' > 'larisa');
console.log('l' < 'e');
console.log(`Acum studiem ${'JavaScript'}.`);
console.log(`Invatam despre ${'string'}.`);
console.log(`${1} kg rosii.
${2} kg cartofi.
${0.5} kg ceapa.`);
